application: euchronism
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /send
  script: euchronism_send.py
  login: admin

- url: /FAQ.html
  script: euchronism_nologin.py

- url: /.*
  script: euchronism_lightrays.py
  login: required

builtins:
- remote_api: on
