application: euchronism
version: live
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /send
  script: euchronism_send.app
  login: admin

- url: /FAQ.html
  script: euchronism_nologin.app

- url: /.*
  script: euchronism_lightrays.app
  login: required

builtins:
- remote_api: on
